name       : python-cookiecutter
version    : 2.1.1
release    : 7
source     :
    - https://github.com/cookiecutter/cookiecutter/archive/refs/tags/2.1.1.tar.gz : 0ef7a3f8c7820be2dc91c7b7d211de26463ab38fcac130350d5f71837bbf0432
homepage   : https://github.com/cookiecutter/cookiecutter
license    : BSD-3-Clause
component  : programming.python
summary    : A command-line utility that creates projects from project templates
description: |
    A command-line utility that creates projects from cookiecutters (project templates), e.g. Python package projects, VueJS projects.
builddeps  :
    - git                 # check
    - python-binaryornot  # check
    - python-click        # check
    - python-freezegun    # check
    - python-jinja2-time  # check
    - python-poyo         # check
    - python-pytest-cov   # check
    - python-pytest-mock  # check
    - python-requests     # check
    - python-slugify      # check
rundeps    :
    - python-binaryornot
    - python-click
    - python-jinja2-time
    - python-poyo
    - python-requests
    - python-slugify
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
